### ISSUE TITLE
Method of killing notification one at a time?

### ISSUE THREAD

**Issue by 676339784** [phillbush/xnotify#8]
While I can send a `pkill -SIGUSR1 xnotify` to clear *all* the notifications, there is no equivalent for if I want to clear one notification at a time. There is the option to clear one notification at a time by clicking on it, but I'm wondering if this functionality can be abstracted out so I can clear one notification at a time with, say, a keybind.

**Comment by phillbush** [comment]
There are two problems on this:

First, there are only two user signals that I can use to send a message to xnotify. One of then is used to close notifications and the other to close and activate it (send its `CMD:` to stdout).

Second, there is no way to specify which notification to close when there is more then one with signals.

So I chose the general case of clearing all notifications at once, since (I think) that is the general use case.

If you have a suggestion of how to send a message to xnotify specifying both to clear and which notification to clear), please comment it.

**Comment by 676339784** [comment]
>If you have a suggestion of how to send a message to xnotify specifying both to clear and which notification to clear, please comment it.

I feel like the which notification part could just be clearing the oldest notification.

And I feel as if it doesn't have to be signals that clear the oldest notification. Could there be another sort of solution? Let me know your thoughts.

**Comment by phillbush** [comment]
I think I'll keep the general case of killing all notifications at once until killing one per time be requested by more users.

But it only requires replacing one line with other two in the code to kill the oldest notification when sending SIGUSR1.  You can apply this diff on your xnotify.c.  
Here's the diff:

```
diff --git a/xnotify.c b/xnotify.c
index 94446db..83b9cb2 100644
--- a/xnotify.c
+++ b/xnotify.c
@@ -1298,7 +1298,8 @@ main(int argc, char *argv[])
 		if (usrflag) {
 			if (usrflag > 1 && queue->head)
 				cmditem(queue->head);
-			cleanitems(queue, NULL);
+			if (queue->head)
+				delitem(queue, queue->head);
 			usrflag = 0;
 		}
 		timeitems(queue);
```
