### ISSUE TITLE
The "height" geometry option is no longer used

### ISSUE THREAD

**Issue by CRImier** [phillbush/xnotify#9]
At some point between 11/11 and today, the "height" geometry option broke - it's longer taken into account and notification height became purely dynamic (and, with the font used automatically on my install, lower half of the font is clipped off). It works for me with a hacky patch that's specific to my setup, but you might want to account for this in some way.

**Comment by phillbush** [comment]
You're right, I ignored `queue->h` on commit [f5d8c09](https://github.com/phillbush/xnotify/commit/f5d8c0974b5e78de01c2a3e71c4d66d0963f92d0) (Dec 10) when I added a dynamic way of computing the height based on the height of the font and the number of lines of content.  I was supposed to check `queue->h` after computing the dynamic height, but I forgot it.

Thanks for noticing that.

What do you think in reconsidering `queue->h`, but as a minimum height (since now the height can grow with the content) rather than the height itself?
